name: eternallands
version: '1.9.5.p3'
summary: Eternal Lands is a free to play, graphical MMORPG
description: |
  Eternal Lands is a free to play, graphical MMORPG (massively-multi-player
  online role-playing game).  Different from other role-playing games, there are
  no fixed classes so you can improve any of the many skills.  There is a choice
  of several character races but all are equal.
  See http://www.eternal-lands.com/
grade: stable
confinement: strict
type: app
icon: pkgfiles/snap-package/eternallands.png

parts:
  client:
    source: https://github.com/raduprv/Eternal-Lands
    source-type: git
    source-tag: 1.9.5.3
    build-packages: [build-essential, libcal3d12-dev, libsdl-image1.2-dev, libsdl-net1.2-dev, libxml2-dev, libopenal-dev, libvorbis-dev]
    plugin: make
    makefile: Makefile.linux
    make-parameters: ["release", "PLATFORM=''", "EXE=el.linux.bin"]
    override-pull: |
      snapcraftctl pull
      sed -i 's|^PLATFORM=.*$|#PLATFORM=""|g' make.defaults
    artifacts: ["el.linux.bin"]
    stage-packages:
      - libglib2.0-0
      - libsdl-net1.2
      - libxml2
      - libogg0
      - libvorbis0a
      - libvorbisfile3
      - libopenal1
      - libcal3d12v5
      - libsdl-image1.2
      - libxrandr2
      - zlib1g
      - libpng16-16
      - libegl1-mesa
      - libglu1-mesa
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglapi-mesa
      - libgles2-mesa
      - libosmesa6
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - mesa-vulkan-drivers
    after:
      - desktop-glib-only

  data:
    source: https://github.com/raduprv/Eternal-Lands/releases/download/1.9.5.2/el_195_1_data_files.zip
    source-checksum: md5/e42ebe628e704c8f7e0b21e3340f475d
    plugin: dump
    organize:
      el_data/ : data/
    override-build: |
      snapcraftctl build
      sed -i 's|^#browser.*$|#browser = x-www-browser|g' $SNAPCRAFT_PART_INSTALL/el_data/el.ini
      sed -i 's|^#use_new_selection.*$|#use_new_selection = 1|g' $SNAPCRAFT_PART_INSTALL/el_data/el.ini

  sound:
    source: https://github.com/raduprv/Eternal-Lands/releases/download/1.9.5.2/eternallands-sound_1.9.4.zip
    source-checksum: md5/28678c3fce12780859ab29d673658681
    plugin: dump
    organize:
      '*' : data/

  music:
    source: https://github.com/raduprv/Eternal-Lands/releases/download/1.9.5.2/music_full.zip
    source-checksum: md5/95220e0df0be0eb4f2b9646cc5d6b7e5
    plugin: dump
    organize:
      '*' : data/music/

  launcher:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -p pkgfiles/snap-package/launcher.sh $SNAPCRAFT_PART_INSTALL/bin/
      cp -p pkgfiles/snap-package/eternallands.desktop $SNAPCRAFT_PART_INSTALL/bin/

apps:
  client:
    plugs:
      - x11
      - opengl
      - network
      - pulseaudio
      - desktop
    desktop: bin/eternallands.desktop
    command: desktop-launch $SNAP/bin/launcher.sh $*
